[Credentials]
# 登录账号
account = 15819893256

# 登录密码
password = ****

[Query]
# 查询的起始时间 (格式: YYYY-MM-DD HH:mm:ss)
start_time = 2026-01-23 00:00:00

# 查询的结束时间 (格式: YYYY-MM-DD HH:mm:ss)
end_time = 2026-04-23 23:59:59

# 需要导出的工单类型，多个类型用英文逗号隔开，全量抓取请填 "全部"
categories = 维修工单,退货退款工单,以货换货工单,换货补发工单,供应商补件工单,部分退款工单,自制补件工单,投诉工单,差评工单

# ================= 9大业务状态开关 =================
# 配置说明：1 = 勾选该条件（仅查询该状态），0 = 不限制（查全部）
# 我的工单
my_ticket = 0

# 异常工单
is_abnormal = 0

# 逾期工单
is_overtime = 0

# 加急工单
is_urgent = 0

# 需理赔工单
need_claim = 0

# 驳回工单
is_reject = 0

# 退回工单
is_back = 0

# 已收货工单
has_recvice = 0

# 拼单工单
has_spell = 0
