[Credentials]
# 登录账号
account = minhua@17817256109

# 登录密码（填入真实明文密码即可，代码会自动转 MD5 加密）
password = ****

[Query]
# 查询的起始时间 (格式: YYYY-MM-DD HH:mm:ss)
start_time = 2026-01-23 00:00:00

# 查询的结束时间 (格式: YYYY-MM-DD HH:mm:ss)
end_time = 2026-04-23 23:59:59

# 【新增配置】需要导出的工单类型，多个类型用英文逗号隔开，全量抓取请直接填 "全部"
# 示例：categories = 维修工单,退货退款工单,催发货工单
categories = 全部
